### ISSUE TITLE
Error while opening capb2b file in dev container

### ISSUE THREAD

**Issue by Umamaheswari252** [qmacro/capb2b#2]
Firstly, I opened capb2b folder in dev container successfully. Somehow, I closed capb2b folder.
I followed the below steps.
Opened capb2b folder again, this time dev container didn't open automatically. So I manually opened capb2bin dev container using f1 key.
I deleted the files and downloadedcapb2b from git again and tried.
Wherever I am placing the folder, I am getting below error
![Screenshot 2024-06-14 212034](https://github.com/qmacro/capb2b/assets/61020596/887d8a9b-b14b-4dc8-bb53-cfec8bec1df1)

Please help me

**Comment by qmacro** [comment]
Hi there, thanks for logging the issue here as requested 👍 I've just tested a fresh clone of this repo and opened it successfully in VS Code on my machine. 

The error message you underline here does highlight something a little suspicious which may be related to the problem you're having: the `capb2b-main` directory name is a clue that you didn't clone the repo but downloaded it, as a ZIP file, via the green "Code" button on the main repo page. This should work too, to be honest, but there's something amiss with your setup in that the downloaded and unzipped directory is not there. Did you delete it? Is it still there? In this directory there should be the `.devcontainer/` subdirectory which VS Code uses to open the repo in a container.

**Comment by Umamaheswari252** [comment]
Hi Dj,
 Yes, I downloaded as ZIP file via the green "Code" button. I extracted the Zip file. Yes, I have extracted file and .devcontainer/ in that folder.
 
I tried to clone the repo, but unfortunately no luck. Could you please how you clone the repo. I will try that option.

**Comment by qmacro** [comment]
You can use different approaches, they're all shown in the popup when you press the button:

![Screenshot 2024-06-21 at 07 56 57](https://github.com/qmacro/capb2b/assets/73068/daaece6b-dbeb-4ebd-8695-0e73cc651150)
